name: 080-resusable-workflow-called

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a hello world script
        run: echo Hello, ${{ inputs.username }}
