name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs: 
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project
